### ISSUE TITLE
issue installing requirments

### ISSUE THREAD

**Issue by FantasticMrCat42** [TencentARC/PhotoMaker#10]
```
C:\AI\PhotoMaker\PhotoMaker>pip install -r requirements.txt
Requirement already satisfied: torch==2.0.1 in c:\users\henso\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: torchvision==0.15.2 in c:\users\henso\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (0.15.2)
ERROR: Could not find a version that satisfies the requirement pytorch-cuda==11.8 (from versions: none)
ERROR: No matching distribution found for pytorch-cuda==11.8

C:\AI\PhotoMaker\PhotoMaker>
```
I tried editing the requirements file but still ran into issues. any solutions?

**Comment by signalstop** [comment]
same issue here.

**Comment by nicekate** [comment]
考虑使用虚拟环境：为了避免潜在的包冲突，建议在 Python 虚拟环境中进行安装。你可以使用 virtualenv 或 conda 来创建一个隔离的环境。

**Comment by steverhoades** [comment]
If you have the requirements installed for diffusers you should be able to bypass the requirements.txt file. At least, it worked for me without it. (no venv).

**Comment by yinghanzi** [comment]
如果安装过pytorch，要把里面的去掉……

**Comment by Kallamamran** [comment]
I used this for an earlier version and it worked:

pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118

I'm on python 3.8 in this install

**Comment by qaisarehman** [comment]
> I used this for an earlier version and it worked:
> 
> pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118
> 
> I'm on python 3.8 in this install

I tried this but facing this issue:
```

Traceback (most recent call last):
  File "app.py", line 10, in <module>
    import spaces
  File "e:\photomaker_ws\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "e:\photomaker_ws\lib\site-packages\spaces\zero\decorator.py", line 18, in <module>
    from .wrappers import regular_function_wrapper
  File "e:\photomaker_ws\lib\site-packages\spaces\zero\wrappers.py", line 42, in <module>
    Process = multiprocessing.get_context('fork').Process
  File "e:\photomaker_ws\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "e:\photomaker_ws\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

**Comment by Kallamamran** [comment]
Check this thread: https://github.com/TencentARC/PhotoMaker/issues/22

**Comment by Paper99** [comment]
Hello everyone, first of all, thank you for your discussions, which helped us fix many known issues in environment construction (in the latest version).

Now, you could update the environment building through:
```bash
conda create --name photomaker python=3.10
pip install -U pip

# Install requirements
pip install -r requirements.txt

# Install photomaker
pip install git+https://github.com/TencentARC/PhotoMaker.git
```

Then you can run the following command to use our PhotoMaker:
```python
from photomaker import PhotoMakerStableDiffusionXLPipeline
```

The previous line can also be used outside the repo.
