### ISSUE TITLE
Gradio demo fails to start

### ISSUE THREAD

**Issue by ThomasHezard** [TencentARC/PhotoMaker#157]
Just tried to start the demo with PhotoMaker v2, but keeps getting the following error (I replaced the private paths with `[...]`):
```bash
Traceback (most recent call last):
  File "[...]/PhotoMaker/gradio_demo/app.py", line 14, in <module>
    from photomaker import PhotoMakerStableDiffusionXLPipeline
  File "[...]/envs/photomaker/lib/python3.10/site-packages/photomaker/__init__.py", line 2, in <module>
    from .model_v2 import PhotoMakerIDEncoder_CLIPInsightfaceExtendtoken
  File "[...]/envs/photomaker/lib/python3.10/site-packages/photomaker/model_v2.py", line 9, in <module>
    from . import FacePerceiverResampler
ImportError: cannot import name 'FacePerceiverResampler' from partially initialized module 'photomaker' (most likely due to a circular import) ([...]/envs/photomaker/lib/python3.10/site-packages/photomaker/__init__.py)
```

I installed the env as explained in the README:
```python
conda create --name photomaker python=3.10
conda activate photomaker
pip install -U pip

# Install requirements
pip install -r requirements.txt

# Install photomaker
pip install git+https://github.com/TencentARC/PhotoMaker.git
```

I ther something I did wrong?

**Comment by Paper99** [comment]
Hi, may be this [PR](https://github.com/TencentARC/PhotoMaker/pull/153) could help you.

**Comment by ThomasHezard** [comment]
Yep, the PR fixed it, thanks 🙏
