### ISSUE TITLE
cannot import name 'FacePerceiverResampler' 

### ISSUE THREAD

**Issue by tom729** [TencentARC/PhotoMaker#159]
python inference_scripts/inference_pmv2.py 
Traceback (most recent call last):
  File "/Users/tangzhenhua/Downloads/lab/PhotoMaker/inference_scripts/inference_pmv2.py", line 10, in <module>
    from photomaker import PhotoMakerStableDiffusionXLPipeline
  File "/Users/tangzhenhua/miniconda3/envs/photomaker/lib/python3.10/site-packages/photomaker/__init__.py", line 2, in <module>
    from .model_v2 import PhotoMakerIDEncoder_CLIPInsightfaceExtendtoken
  File "/Users/tangzhenhua/miniconda3/envs/photomaker/lib/python3.10/site-packages/photomaker/model_v2.py", line 9, in <module>
    from . import FacePerceiverResampler
ImportError: cannot import name 'FacePerceiverResampler' from partially initialized module 'photomaker' (most likely due to a circular import) (/Users/tangzhenhua/miniconda3/envs/photomaker/lib/python3.10/site-packages/photomaker/__init__.py)

**Comment by Paper99** [comment]
Try this line `from .resampler import FacePerceiverResampler`

**Comment by ThomasHezard** [comment]
See https://github.com/TencentARC/PhotoMaker/issues/157, the commit from a few hours ago fixed it
