### ISSUE TITLE
load_ip_adapter cannot load ip-adapter-faceid-plusv2_sdxl.bin

### ISSUE THREAD

**Issue by doublexxking** [TencentARC/PhotoMaker#169]
My code:
`pipe.load_ip_adapter("h94/IP-Adapter-FaceID", subfolder="", weight_name="ip-adapter-faceid-plusv2_sdxl.bin")`
It gives error:

ip-adapter-faceid-plusv2_sdxl.bin: 100%|█████████████████████████████████████████████████████████| 1.49G/1.49G [01:47<00:00, 13.8MB/s]
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/venv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/image_encoder/config.json

Is there something wrong with my code?

**Comment by doublexxking** [comment]
I check the files in huggingface, https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models 
I change to 
pipe.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter-plus-face_sdxl_vit-h.bin")

it gives the following error
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1028x1664 and 1280x1280)

Is there some method to use ip-adapter-plus-face_sdxl with PhotoMakerV2?
