### ISSUE TITLE
运行 python gradio_demo/app.py  报错

### ISSUE THREAD

**Issue by yangcw** [TencentARC/PhotoMaker#190]
File "/opt/anaconda3/envs/photomaker/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/opt/anaconda3/envs/photomaker/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/anaconda3/envs/photomaker/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

**Comment by tian685** [comment]
Traceback (most recent call last):
  File "/opt/miniconda3/envs/oce/lib/python3.9/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/opt/miniconda3/envs/oce/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/miniconda3/envs/oce/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
