### ISSUE TITLE
Problem running Gradio demo

### ISSUE THREAD

**Issue by Kallamamran** [TencentARC/PhotoMaker#22]
I've cloned PhotoMaker and installed a venv of Python 3.8.
All requirements has installed ok with help of an earlier version of pytorch since I got this first:

**(venv) Q:\PhotoMaker>pip install -r requirements.txt**
<code style="color : green">Collecting torch==2.0.1
  Downloading torch-2.0.1-cp38-cp38-win_amd64.whl (172.4 MB)
     |████████████████████████████████| 172.4 MB 6.4 MB/s
Collecting torchvision==0.15.2
  Downloading torchvision-0.15.2-cp38-cp38-win_amd64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 6.4 MB/s</code>
<code style="color : red">ERROR: Could not find a version that satisfies the requirement pytorch-cuda==11.8 (from versions: none)</code>
<code style="color : red">ERROR: No matching distribution found for pytorch-cuda==11.8</code>

**Using older version of torch at least the installation worked:**

<code style="color : green">pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118</code>

**Now I have this error trying to run the Gradio demo though:**

**(venv) Q:\PhotoMaker>python gradio_demo/app.py**
<code style="color : red">Traceback (most recent call last):
  File "gradio_demo/app.py", line 10, in <module>
    import spaces
  File "Q:\PhotoMaker\venv\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "Q:\PhotoMaker\venv\lib\site-packages\spaces\zero\decorator.py", line 18, in <module>
    from .wrappers import regular_function_wrapper
  File "Q:\PhotoMaker\venv\lib\site-packages\spaces\zero\wrappers.py", line 42, in <module>
    Process = multiprocessing.get_context('fork').Process
  File "C:\Users\Kallamamran\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\Users\Kallamamran\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'</code>

I wonder what's wrong :(

**Comment by nitrosocke** [comment]
This seems to be an issue with `spaces` on windows. Somewhat related to this: [https://github.com/woven-planet/l5kit/issues/129](Issue #129)
I solved it by editing line 42 in `venv\Lib\site-packages\spaces\zero\wrappers.py` from:
`Process = multiprocessing.get_context('fork').Process` to
`Process = multiprocessing.get_context('spawn').Process`

Also needed to drag the `photomaker` directory containing the pipeline into the `gradio_demo` folder.
Not sure if this is the ideal solution but a workaround on windows.

**Comment by NolenBrolen** [comment]
Also changed the line of code from 'fork' to 'spawn' but I still get a similar ModuleNotFoundError
`(venv-photomaker) C:\Users\G4G\PhotoMaker>python gradio_demo/app.py
Traceback (most recent call last):
  File "C:\Users\G4G\PhotoMaker\gradio_demo\app.py", line 13, in <module>
    from photomaker.pipeline import PhotoMakerStableDiffusionXLPipeline
ModuleNotFoundError: No module named 'photomaker'`

**Comment by Kallamamran** [comment]
I had to install photomaker by "pip install photomaker" to get past that error, but I still have error I just posted about 🤔

**Comment by tdslaine** [comment]
> I've done the fork -> spawn thing, but that still gives me an error
> 
> (venv) Q:\PhotoMaker>python gradio_demo/app.py Traceback (most recent call last): File "gradio_demo/app.py", line 17, in from photomaker.pipeline import PhotoMakerStableDiffusionXLPipeline ModuleNotFoundError: No module named 'photomaker.pipeline'
> 
> Will try moving the folder...

I had to put all files from photomaker folder into the root where app.py is located @, removing the subfolder photomaker completly and adjusting the app.py as well as the pipeline.py to not look inside photomaker. folder for the modules 


so it looks like:

 - gradio_demo:
    >app.py
    >model.py
    >pipeline.py
    >sytle_template.py

I also had to change:

line **22 in pipeline.py**
original: **from photomaker.model import PhotoMakerIDEncoder**
altered: from model import PhotoMakerIDEncoder

and
line **14 in app.py**
original: **from photomaker.pipeline import PhotoMakerStableDiffusionXLPipeline**
altered:  **from pipeline import PhotoMakerStableDiffusionXLPipeline**

**Comment by NolenBrolen** [comment]
> I had to install photomaker by "pip install photomaker" to get past that error, but I still have error I just posted about 🤔

This won't work cuz it's another library you're installing, which is used to make funny pictures https://pypi.org/project/photomaker/

I just tried the following:
- in terminal type "Python" or "Python3"
- then paste the code to download the models from huggingface: from huggingface_hub import hf_hub_download
photomaker_path = hf_hub_download(repo_id="TencentARC/PhotoMaker", filename="photomaker-v1.bin", repo_type="model")
- It's currently downloading so hope this fixes it

**Comment by tdslaine** [comment]
> > I had to install photomaker by "pip install photomaker" to get past that error, but I still have error I just posted about 🤔
> 
> This won't work cuz it's another library you're installing, which is used to make funny pictures https://pypi.org/project/photomaker/
> 
> I just tried the following:
> 
>     * in terminal type "Python" or "Python3"
> 
>     * then paste the code to download the models from huggingface: from huggingface_hub import hf_hub_download
>       photomaker_path = hf_hub_download(repo_id="TencentARC/PhotoMaker", filename="photomaker-v1.bin", repo_type="model")
> 
>     * It's currently downloading so hope this fixes it
> 
> 
> Edit: installing the models did not fix the ModuleNotFoundError: No Module named 'photomaker'

try my solution -with all files into the gradient_demo folder, and adjusting the two .py files to not look into the photomaker studio as described above. it works for me until now - gotta wait for the download to finish

![grafik](https://github.com/TencentARC/PhotoMaker/assets/46573429/aefe2013-dd1f-4f62-8f30-653d835d7864)

**Comment by Syndulla** [comment]
Let us know if you get reasonable outputs. I followed the approach above and got Gradio running, but my outputs are a blobby brown noise.

**Comment by Kallamamran** [comment]
Yepp... Worked...

1. Change line 42 in <code style="color : green">venv\Lib\site-packages\spaces\zero\wrappers.py</code> from <code style="color : green">Process = multiprocessing.get_context('fork').Process</code> to <code style="color : green">Process = multiprocessing.get_context('spawn').Process</code>

2. move the files in <code style="color : green">photomaker-dir</code> to <code style="color : green">gradio_demo</code>

3. remove original photomaker-dir

4. Change line 22 in pipeline.py from <code style="color : green">from photomaker.model import PhotoMakerIDEncoder</code> to <code style="color : green">from model import PhotoMakerIDEncoder</code>

5. Change line 14 in app.py from <code style="color : green">from photomaker.pipeline import PhotoMakerStableDiffusionXLPipeline</code> to <code style="color : green">from pipeline import PhotoMakerStableDiffusionXLPipeline</code>

**Comment by justinjohn0306** [comment]
> Process = multiprocessing.get_context('fork').Process

Use python 3.10 or add these line in app.py : 

add this line at the top ---> ``from typing import Tuple``

find this line ---> ``def apply_style(style_name: str, positive: str, negative: str = "") -> tuple[str, str]:``

and replace with this one ---> ``def apply_style(style_name: str, positive: str, negative: str = "") -> Tuple[str, str]:``

**Comment by tdslaine** [comment]
> > Process = multiprocessing.get_context('fork').Process
> 
> Use python 3.10 or add these line in app.py :
> 
> add this line at the top ---> `from typing import Tuple`
> 
> find this line ---> `def apply_style(style_name: str, positive: str, negative: str = "") -> tuple[str, str]:`
> 
> and replace with this one ---> `def apply_style(style_name: str, positive: str, negative: str = "") -> Tuple[str, str]:`
> 
> it works for me :)
> <img alt="image" width="1902" src="https://private-user-images.githubusercontent.com/34035011/297063027-e0261180-d356-48c5-87cc-9378448dc85b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTEzMjYsIm5iZiI6MTcwNTQxMTAyNiwicGF0aCI6Ii8zNDAzNTAxMS8yOTcwNjMwMjctZTAyNjExODAtZDM1Ni00OGM1LTg3Y2MtOTM3ODQ0OGRjODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzMTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTk3YzAxMzQxYzZmNzYyOWY0YTNkMGUxNTM3NDYxYTJhMjJkMzliOTMwZTllYzgyYzM2YjEyYjkwMmJhNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQQhw0xt59a-uyBmhLJ68g8JhmHagQG8MZ8Nl-YDbBY">

yes, bad entry in readme - shoudl state required python 3.9 - this Tulpe error been the last error - now onto the stylized version :D

**Comment by Kallamamran** [comment]
Gradio interface works, but still... Nope
Uploaded an image, but when trying to generate I only get this:

Traceback (most recent call last):
  File "Q:\PhotoMaker\venv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "Q:\PhotoMaker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "Q:\PhotoMaker\venv\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "Q:\PhotoMaker\venv\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "Q:\PhotoMaker\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "Q:\PhotoMaker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "Q:\PhotoMaker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "Q:\PhotoMaker\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "Q:\PhotoMaker\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "gradio_demo/app.py", line 55, in generate_image
    raise gr.Error(f"Cannot find the trigger word '{pipe.trigger_word}' in text prompt! Please refer to step 2️⃣")
gradio.exceptions.Error: "Cannot find the trigger word 'img' in text prompt! Please refer to step 2️⃣"

**Comment by xhoxye** [comment]
`E:\AI\Fooocus\PhotoMaker>.\python_embeded\python.exe -s PhotoMaker/app.py
Traceback (most recent call last):
  File "E:\AI\Fooocus\PhotoMaker\PhotoMaker\app.py", line 10, in <module>
    import spaces
  File "E:\AI\Fooocus\PhotoMaker\python_embeded\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "E:\AI\Fooocus\PhotoMaker\python_embeded\lib\site-packages\spaces\zero\decorator.py", line 17, in <module>
    from . import client
  File "E:\AI\Fooocus\PhotoMaker\python_embeded\lib\site-packages\spaces\zero\client.py", line 17, in <module>
    from .gradio import get_event
  File "E:\AI\Fooocus\PhotoMaker\python_embeded\lib\site-packages\spaces\zero\gradio.py", line 8, in <module>
    from gradio.context import LocalContext
ImportError: cannot import name 'LocalContext' from 'gradio.context' (E:\AI\Fooocus\PhotoMaker\python_embeded\lib\site-packages\gradio\context.py)`

**Comment by dancemanUK** [comment]
Built Distributions
[photomaker-1.0.1-py3-none-any.whl ](https://files.pythonhosted.org/packages/41/5d/4f79fcca13f366f4b0188ec1c02c896a5da450c0818a2405d7d0ba00387c/photomaker-1.0.1-py3-none-any.whl)(4.1 kB [view hashes](https://pypi.org/project/photomaker/#copy-hash-modal-bab9b984-3ad0-42b9-9439-35f6470ba21f))
Uploaded Nov 18, 2022 py3

[photomaker-1.0.1-1-py3-none-any.whl ](https://files.pythonhosted.org/packages/ce/a6/c1eca09f99b5b9f36d126e026bef4203289df309d27b207f88a58255157e/photomaker-1.0.1-1-py3-none-any.whl)(3.1 MB [view hashes](https://pypi.org/project/photomaker/#copy-hash-modal-46651f57-563c-4e7c-a830-624523f55335))
Uploaded Nov 18, 2022 py3

<img width="1575" alt="wechat_20240117181712" src="https://github.com/TencentARC/PhotoMaker/assets/1702623/fef6050a-5b80-4f2b-bd0b-56b7dd7e1aa2">


<img width="1250" alt="wechat_20240117181733" src="https://github.com/TencentARC/PhotoMaker/assets/1702623/68ea7904-4ea9-4cfe-b643-fa50a9156c77">
<img width="488" alt="wechat_20240117181806" src="https://github.com/TencentARC/PhotoMaker/assets/1702623/9e9adcfc-2530-44f7-9f26-9a7ca9b11b6f">

**Comment by xhoxye** [comment]
@dancemanUK
Please ask, why I downloaded the file according to your screenshot, and there is no response after it can be run, why is this?

**Comment by seoeaa** [comment]
Guys, you don’t need to be tricky, just put the file in the root and that’s it, change the extension to .py
[app1.txt](https://github.com/TencentARC/PhotoMaker/files/13981659/app1.txt)

**Comment by seoeaa** [comment]
and put the style file in the root too
