### ISSUE TITLE
ValueError: cannot find context for 'fork' 

### ISSUE THREAD

**Issue by frzqwerty** [TencentARC/PhotoMaker#56]
I am getting that a error.  Can anyone help me?
  
(base) C:\Users\QWERTY\Desktop\PhotoMaker-main>python gradio_demo/app.py
Traceback (most recent call last):
  File "C:\Users\QWERTY\Desktop\PhotoMaker-main\gradio_demo\app.py", line 10, in <module>
    import spaces
  File "C:\Users\QWERTY\anaconda3\Lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "C:\Users\QWERTY\anaconda3\Lib\site-packages\spaces\zero\decorator.py", line 18, in <module>
    from .wrappers import regular_function_wrapper
  File "C:\Users\QWERTY\anaconda3\Lib\site-packages\spaces\zero\wrappers.py", line 42, in <module>
    Process = multiprocessing.get_context('fork').Process
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\QWERTY\anaconda3\Lib\multiprocessing\context.py", line 243, in get_context
    return super().get_context(method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\QWERTY\anaconda3\Lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

**Comment by Paper99** [comment]
You could refer to #41.
