### ISSUE TITLE
 PhotoMakerStableDiffusionXLPipeline.from_pretrained() download error

### ISSUE THREAD

**Issue by beria-moon** [TencentARC/PhotoMaker#68]
Fetching 18 files:  17%|██████████▌                                                    | 3/18 [00:01<00:05,  2.52it/s]
Traceback (most recent call last):
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangjinting/A-V/PhotoMaker/gradio_demo/app.py", line 27, in <module>
    pipe = PhotoMakerStableDiffusionXLPipeline.from_pretrained(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1100, in from_pretrained
    cached_folder = cls.download(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1861, in download
    cached_folder = snapshot_download(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 94, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 283, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
    http_get(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 451, in http_get
    r = _request_wrapper(
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/home/wangjinting/anaconda3/envs/py3.8/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 59325157-ca34-4fc9-98b3-f7b42c3a85bd)')

**Comment by Sqlver** [comment]
You can try export HF_HUB_ENABLE_HF_TRANSFER=False
