### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by hgabha** [TencentARC/PhotoMaker#88]
As per the instructions I'm getting error at Step 4 with requirements.txt. Is there an undoucmented step before to clone GIT?? If so can the correct steps be updated pls!

conda create --name photomaker python=3.10
conda activate photomaker
pip install -U pip

# Install requirements
**pip install -r requirements.txt**

# Install photomaker
pip install git+https://github.com/TencentARC/PhotoMaker.git

(photomaker) C:\Users\hg>pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by hgabha** [comment]
if I clone git before running requirements.txt then I can get through the install but now it falls over at launch.

(photomaker) C:\Users\Harmeet\anaconda3\envs\photomaker>python photomaker/gradio_demo/app.py
Traceback (most recent call last):
  File "C:\Users\Harmeet\anaconda3\envs\photomaker\photomaker\gradio_demo\app.py", line 11, in <module>
    import spaces
  File "C:\Users\Harmeet\anaconda3\envs\photomaker\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "C:\Users\Harmeet\anaconda3\envs\photomaker\lib\site-packages\spaces\zero\decorator.py", line 18, in <module>
    from .wrappers import regular_function_wrapper
  File "C:\Users\Harmeet\anaconda3\envs\photomaker\lib\site-packages\spaces\zero\wrappers.py", line 42, in <module>
    Process = multiprocessing.get_context('fork').Process
  File "C:\Users\Harmeet\anaconda3\envs\photomaker\lib\multiprocessing\context.py", line 243, in get_context
    return super().get_context(method)
  File "C:\Users\Harmeet\anaconda3\envs\photomaker\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

Appreciate any help in fixing this!!

**Comment by hgabha** [comment]
I run SD web ui with my local install all the time and never have issues with them

**Comment by TheMindExpansionNetwork** [comment]
same issue hmmmmmm not sure what could cause not sure if it is cuz I forked it

**Comment by Paper99** [comment]
Please refer to #41

**Comment by Paper99** [comment]
https://github.com/TencentARC/PhotoMaker/issues/59#issuecomment-1898309857

**Comment by hgabha** [comment]
Solution is to use this repo https://github.com/bmaltais/PhotoMaker
