### ISSUE TITLE
how to solve? need help

### ISSUE THREAD

**Issue by zxilin01** [TencentARC/PhotoMaker#92]
Traceback (most recent call last):
  File "/Users/zhengxilin01/Desktop/PhotoMaker-main2/test.py", line 53, in <module>
    images = pipe(
  File "/Users/zhengxilin01/miniconda3/envs/PhotoMaker-main/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/zhengxilin01/Desktop/PhotoMaker-main2/photomaker/pipeline.py", line 338, in __call__
    ) = self.encode_prompt_with_trigger_word(
  File "/Users/zhengxilin01/Desktop/PhotoMaker-main2/photomaker/pipeline.py", line 196, in encode_prompt_with_trigger_word
    clean_input_ids = clean_input_ids + [tokenizer.pad_token_id] * (max_len - len(clean_input_ids))
OverflowError: cannot fit 'int' into an index-sized integer

i think maybe "max_len" is too large, but after changing it, the project can run, but can't output result.

**Comment by Paper99** [comment]
How to replicate this error?

**Comment by zxilin01** [comment]
I print the ’tokenizer.model_max_length‘, and it is 1000000000000000019884624838656. Can i modify it? Why it is so large

**Comment by baimazhaoge** [comment]
i meet this error too, how to solve it?
